### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by glaubinix** [glaubinix/conference-schedule#10]
@kiltec mentioned that he might be interested in writing some tests (because we do have non so far). Question now what library / framework would be want?

My suggestion would be Jasmine.

**Comment by BattleRattle** [comment]
I've never worked with any JS test framework before (except the [Codewars kata test framework](https://github.com/codewars/kata-test-framework-js), which is written for NodeJS), so I can't suggest any.

At first sight Jasmine looks pretty good to me. I like the API.

+1 for Jasmine

**Comment by kiltec** [comment]
I like the one used at Codewars (which might be https://github.com/visionmedia/mocha ) but I don't really care... :smiley: 

So, Jasmine it is?

**Comment by BattleRattle** [comment]
> I like the one used at Codewars (which might be https://github.com/visionmedia/mocha ) but I don't really care... :smiley:

At Codewars they use a self-written framework, which I've linked in the comment above yours :smile:
But Jasmine seems to have a similar API, so I think yes, Jasmine it is

**Comment by kiltec** [comment]
Ok, cool!

Hm, I think then the next question is related issue #8 - it would be nice if the tests were run by some kind of build tool. Just checked, there's a Jasmine plugin for Grunt.

Well, I will start writing tests anyways but still... :D
