### ISSUE TITLE
Add conference schedule to Code Climate

### ISSUE THREAD

**Issue by kiltec** [glaubinix/conference-schedule#19]
Since a couple of days Code Climate also supports JS, it looks pretty useful and it's free for OSS projects:
http://blog.codeclimate.com/blog/2013/10/24/code-climate-for-javascript/

What do you think?

**Comment by BattleRattle** [comment]
I'm not sure, if this is that useful for a small project like this one. But on the other hand, it doesn't hurt, right? So I'm pretty undecided regarding this one. Maybe you have some arguments for or against that? :)

**Comment by glaubinix** [comment]
I will have to have a look at it first. Never really had the chance to do that yet. Therefore I am not yet sure what we would gain from it.

**Comment by kiltec** [comment]
I'm not sure either! :-D
But might be good opportunity to learn how useful it is.
Am 26.10.2013 23:10 schrieb "Stephan Vock" notifications@github.com:

**Comment by glaubinix** [comment]
I do not see this happening at the moment.
