### ISSUE TITLE
Add a config file

### ISSUE THREAD

**Issue by glaubinix** [glaubinix/conference-schedule#5]
We should add a config file where you can specify a couple of things. Like:
-json or spreadsheet (or even something else)
-json name, spreadsheet id

Maybe even add stylesheet, title, ...

**Comment by glaubinix** [comment]
Hey, I added the config file and I am using every thing defined in the file already (apart from the theme). Today I introduced the PageBuilder object. Idea is that everything that can be configured via the config file gets a method in the PageBuilder.

This would make it really easy to change config params on the fly and it will enable us to move a lot of logic out of the main.js file.

Any ideas what else could be moved to the config file? Maybe the a flag to disable to star/unstar feature if someone does not like it, click on expand, pull to refresh?

**Comment by BattleRattle** [comment]
Hmm, maybe the "star/unstar" feature could be a kind of plugin? It could be a single JS-file ("js/plugins/star.js" or similar) and in the config we would have an array of used plugins?

**Comment by glaubinix** [comment]
uuhh cool idea. I will think about how we can make the system plugable. Main issue is still that we kind of generate the content twice. I think I need to solve that issue first.

**Comment by glaubinix** [comment]
I am pretty sure that I implemented everything we discussed. Could you maybe have a look at it.
Just be warned: A lot changed today.

**Comment by BattleRattle** [comment]
Wow, looks really great! :+1:
I was really surprised, when I saw all those changes. But I like it :)

**Comment by glaubinix** [comment]
Ok, then I'll close the ticket
